# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cervejada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.IntegerField()),
                ('tempo_corrida', models.IntegerField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
